### ISSUE TITLE
AddProviders does not work with RestEasy Reactive

### ISSUE THREAD

**Issue by allanhladki** [marcelorubim/quarkus-monitor#21]
As today, quarkus reccomend explicit to use the RestEasy Reactive dependencies instead of JAX-RS [(quarkus guide)](https://quarkus.io/guides/resteasy-reactive).

Trying to use `quarkus-monitor` with jakarta and `jakarta.ws.rs.ext.Provider` results in this error:<br>
```console
Build step br.com.labbs.quarkusmonitor.deployment.QuarkusMonitor#addProviders threw an exception: java.lang.NoClassDefFoundError: javax/ws/rs/container/ContainerRequestFilter
[ERROR]         at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[ERROR]         at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
[ERROR]         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:506)
[ERROR]         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:466)
[ERROR]         at br.com.labbs.quarkusmonitor.deployment.QuarkusMonitor.addProviders(QuarkusMonitor.java:35)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:840)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.lang.ClassNotFoundException: javax.ws.rs.container.ContainerRequestFilter
[ERROR]         at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
[ERROR]         at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
[ERROR]         at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
[ERROR]         at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
[ERROR]         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:516)
[ERROR]         at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:466)
[ERROR]         ... 16 more
```
Since actually, this depency for reactive implementation is not `javax/ws/rs/container/ContainerRequestFilter` anymore.

There is this migration [tutorial](https://quarkus.io/guides/resteasy-reactive-migration), which adresses in the section `Provider registration via Build Items`, this:

> Extensions that register providers via build items use the io.quarkus.resteasy.common.spi.ResteasyJaxrsProviderBuildItem build item in RESTEasy Classic. With RESTEasy Reactive however, extensions need to use specific build items, such as io.quarkus.resteasy.reactive.spi.MessageBodyWriterBuildItem and io.quarkus.resteasy.reactive.spi.MessageBodyWriterBuildItem.

Does this dependency will be updated to use new Jakarta instances, or you recommend to use another solution in this case? 
Thanks.

**Comment by allanhladki** [comment]
Verifiquei a existência do [quarkus-monitor-reactive](https://github.com/labbsr0x/quarkus-monitor-reactive). Estou fechando a issue, obrigado.
